# Generated by Django 4.1.2 on 2022-10-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provincias", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provincia",
            name="nome",
            field=models.CharField(max_length=150, verbose_name="Província"),
        ),
    ]
