# Generated by Django 4.1.2 on 2022-10-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0002_alter_hospital_provincia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital",
            name="nome",
            field=models.CharField(max_length=200, verbose_name="Nome do Hospital"),
        ),
    ]
