# Generated by Django 4.1.2 on 2022-10-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doador", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doador", name="data_nascimento", field=models.DateTimeField(),
        ),
    ]
