# Generated by Django 4.1.2 on 2022-10-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doador", "0003_doador_email_doador_hospital_doador_provincia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doador",
            name="sobrenome",
            field=models.CharField(
                default=1, max_length=150, verbose_name="Sobrenome:"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="doador",
            name="nome",
            field=models.CharField(max_length=150, verbose_name="Primeiro nome:"),
        ),
    ]
