# Generated by Django 4.1.2 on 2022-10-09 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("provincias", "0002_alter_provincia_nome"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospital", "0002_alter_hospital_provincia"),
        ("doador", "0004_doador_sobrenome_alter_doador_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doador",
            name="data_nascimento",
            field=models.DateTimeField(verbose_name="Data de Nascimento"),
        ),
        migrations.AlterField(
            model_name="doador",
            name="email",
            field=models.EmailField(max_length=150, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="doador",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="hospital.hospital",
                verbose_name="Hospital",
            ),
        ),
        migrations.AlterField(
            model_name="doador",
            name="nome",
            field=models.CharField(max_length=150, verbose_name="Primeiro nome"),
        ),
        migrations.AlterField(
            model_name="doador",
            name="provincia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="provincias.provincia",
                verbose_name="Província",
            ),
        ),
        migrations.AlterField(
            model_name="doador",
            name="sobrenome",
            field=models.CharField(max_length=150, verbose_name="Sobrenome"),
        ),
        migrations.AlterField(
            model_name="doador",
            name="telefone",
            field=models.CharField(max_length=25, verbose_name="Número de Telefone"),
        ),
        migrations.AlterField(
            model_name="doador",
            name="ultimo_log",
            field=models.DateTimeField(auto_now=True, verbose_name="Último Login"),
        ),
        migrations.AlterField(
            model_name="doador",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
    ]
