# Generated by Django 4.1.2 on 2022-10-15 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tipo_sangue", "0001_initial"),
        ("hospital", "0003_alter_hospital_nome"),
        ("doador", "0005_alter_doador_data_nascimento_alter_doador_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HospitalDoador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ultima_doacao", models.DateField(auto_created=True)),
                (
                    "doador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="doador.doador"
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hospital.hospital",
                    ),
                ),
                (
                    "tipe_sangue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tipo_sangue.tiposangue",
                    ),
                ),
            ],
        ),
    ]
