# Generated by Django 4.1.2 on 2022-10-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doador", "0006_hospitaldoador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospitaldoador",
            name="ultima_doacao",
            field=models.DateField(auto_created=True, auto_now=True),
        ),
    ]
