# Generated by Django 4.1.2 on 2022-10-15 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doador", "0007_alter_hospitaldoador_ultima_doacao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hospitaldoador", old_name="tipe_sangue", new_name="tipo_sangue",
        ),
    ]
