# Generated by Django 4.1.2 on 2022-10-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doador", "0009_alter_doador_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doador",
            name="data_nascimento",
            field=models.DateField(verbose_name="Data de Nascimento"),
        ),
    ]
