# Generated by Django 4.1.2 on 2022-10-09 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doador", "0004_doador_sobrenome_alter_doador_nome"),
    ]

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Nº documentos:"
                    ),
                ),
                ("file", models.FileField(upload_to="documentos")),
                (
                    "dono",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="doador.doador"
                    ),
                ),
            ],
        ),
    ]
