# Generated by Django 4.1.2 on 2022-10-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Documento",),
    ]
