# Generated by Django 4.1.2 on 2022-10-09 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doador", "0005_alter_doador_data_nascimento_alter_doador_email_and_more"),
        ("documentos", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="dono",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="doador.doador",
                verbose_name="Proprietário",
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="file",
            field=models.FileField(upload_to="documentos", verbose_name="Ficheiro"),
        ),
    ]
