# Generated by Django 4.1.2 on 2022-10-09 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospital", "0002_alter_hospital_provincia"),
        ("familiar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familiar",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hospital.hospital",
                verbose_name="Hospital",
            ),
        ),
        migrations.AlterField(
            model_name="familiar",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
    ]
