# Generated by Django 4.1.2 on 2022-10-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("familiar", "0002_alter_familiar_hospital_alter_familiar_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familiar",
            name="data_nascimento",
            field=models.DateTimeField(verbose_name="Data de Nascimento"),
        ),
        migrations.AlterField(
            model_name="familiar",
            name="email",
            field=models.EmailField(max_length=150, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="familiar",
            name="nome",
            field=models.CharField(max_length=150, verbose_name="Nome do Doador"),
        ),
        migrations.AlterField(
            model_name="familiar",
            name="telefone",
            field=models.CharField(max_length=25, verbose_name="Número de Telefone"),
        ),
    ]
