# Generated by Django 4.1.2 on 2022-10-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "familiar",
            "0003_alter_familiar_data_nascimento_alter_familiar_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="familiar",
            name="ultimo_log",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
